name: japx
description: Lightweight parser for the JSON:API (http://jsonapi.org/) structure.
version: 2.0.3
repository: https://github.com/infinum/flutter-plugins-japx
homepage: https://github.com/infinum/flutter-plugins-japx

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.20.2
